version: 0.1.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
build:
  publish_nuget: true
  verbosity: minimal
test: off